#!/usr/bin/env bash
#The Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

count=0

while [ $count -lt 10 ]
	if [ $count -eq 4]
		echo "bad luck"
	elif [ $count -eq 8 ]
		echo "good luck"
	else
		echo "Best School"
	(( count++ ))
done

